import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'

import Nav from '../components/Nav/Nav.js'
import Category from '../components/Category/Category.js'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Your shopping list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
      <section className="text-gray-600 body-font">
        <Category />
      </section>
      </main>

    </div>
  )
}
